import React, { useState } from "react";
import { genId } from "../data/helpers.js";
import { getToday } from "../data/dateUtils.js";
import { GOAL_CATEGORY_TO_STAT } from "../data/goalQuests.js";
import { useI18n } from "./i18n/I18nProvider.jsx";

// Ziel-Ritual (Paket C): inszenierte Ziel-Erfassung beim Level-5-Unlock.
// Schreibt Ziele exakt im CreateGoalModal-Format; Abbruch erlaubt (Meta-Quest
// aus Paket B bleibt Auffangnetz).

const CATEGORY_LABELS = {
  de: { fitness: "Fitness", learning: "Lernen", health: "Gesundheit", productivity: "Produktiv", social: "Sozial" },
  en: { fitness: "Fitness", learning: "Learning", health: "Health", productivity: "Productive", social: "Social" },
};
const CATEGORY_COLORS = { fitness: "#ef4444", learning: "#3b82f6", health: "#22c55e", productivity: "#f59e0b", social: "#a855f7" };

function emptyDraft() {
  return { key: genId(), category: "fitness", title: "", milestones: ["", "", ""] };
}

export default function GoalRitualModal({ theme, aiAvailable = false, onRequestAISuggestions, onSave, onSkip }) {
  const { t, locale } = useI18n();
  const labels = CATEGORY_LABELS[locale === "en" ? "en" : "de"];
  const [drafts, setDrafts] = useState([emptyDraft()]);
  const [aiState, setAiState] = useState("idle"); // idle | loading | failed
  const [suggestions, setSuggestions] = useState([]);

  const updateDraft = (key, patch) => setDrafts(ds => ds.map(d => d.key === key ? { ...d, ...patch } : d));
  const updateMilestone = (key, idx, value) => setDrafts(ds => ds.map(d => {
    if (d.key !== key) return d;
    const milestones = [...d.milestones];
    milestones[idx] = value;
    return { ...d, milestones };
  }));

  const requestSuggestions = async () => {
    if (!onRequestAISuggestions || aiState === "loading") return;
    setAiState("loading");
    const result = await onRequestAISuggestions();
    if (result && result.length > 0) {
      setSuggestions(result);
      setAiState("idle");
    } else {
      setAiState("failed");
    }
  };

  const adoptSuggestion = (suggestion) => {
    setDrafts(ds => {
      const draft = {
        key: genId(),
        category: suggestion.category,
        title: suggestion.title,
        milestones: [...suggestion.milestones.slice(0, 5), "", ""].slice(0, Math.max(3, suggestion.milestones.length)),
      };
      const emptyIdx = ds.findIndex(d => !d.title.trim());
      if (emptyIdx >= 0) return ds.map((d, i) => i === emptyIdx ? draft : d);
      if (ds.length < 3) return [...ds, draft];
      return ds;
    });
  };

  const validDrafts = drafts.filter(d => d.title.trim());
  const handleConfirm = () => {
    if (validDrafts.length === 0) return;
    const today = getToday();
    const goals = validDrafts.map(d => {
      const milestoneTitles = d.milestones.map(m => m.trim()).filter(Boolean);
      const finalTitles = milestoneTitles.length > 0 ? milestoneTitles : [d.title.trim()];
      return {
        id: "goal_" + genId(),
        title: d.title.trim(),
        description: "",
        category: d.category,
        deadline: "",
        createdAt: today,
        milestones: finalTitles.map(title => ({ id: genId(), title, xpBonus: 50, completed: false })),
        autoGeneratedQuests: true,
      };
    });
    onSave(goals);
  };

  const mono = "'JetBrains Mono',monospace";
  const inputStyle = {
    width: "100%", padding: "10px 12px", borderRadius: 10, fontSize: 13,
    background: "rgba(255,255,255,0.04)", border: "1px solid rgba(148,163,184,0.18)",
    color: "#f1f5f9", outline: "none", fontFamily: "'Outfit',sans-serif",
  };

  return (
    <div style={{ position: "fixed", inset: 0, zIndex: 500, background: "rgba(1,0,6,0.97)", display: "flex", alignItems: "center", justifyContent: "center", padding: 18, animation: "fadeIn 0.4s", overflowY: "auto" }}>
      <div style={{ width: "100%", maxWidth: 420, maxHeight: "92vh", overflowY: "auto", animation: "scaleIn 0.5s cubic-bezier(0.34,1.56,0.64,1)", background: "rgba(10,12,24,0.96)", border: "1px solid rgba(99,102,241,0.22)", borderRadius: 20, padding: "22px 20px", boxShadow: "0 24px 80px rgba(0,0,0,0.6)" }}>
        <div style={{ textAlign: "center", marginBottom: 18 }}>
          <div style={{ fontSize: 9, letterSpacing: 5, color: "#6366f1", fontFamily: mono, marginBottom: 8 }}>{t("quests.goalRitual.eyebrow")}</div>
          <h2 style={{ fontSize: 21, fontWeight: 900, color: "#fff", fontFamily: "'Cinzel',serif", marginBottom: 8, textShadow: "0 0 30px #6366f166" }}>{t("quests.goalRitual.title")}</h2>
          <p style={{ fontSize: 12, color: "#94a3b8", lineHeight: 1.6 }}>{t("quests.goalRitual.intro")}</p>
        </div>

        {aiAvailable && (
          <div style={{ marginBottom: 16, padding: "12px 14px", borderRadius: 14, background: "rgba(99,102,241,0.06)", border: "1px solid rgba(99,102,241,0.18)" }}>
            <button
              onClick={requestSuggestions}
              disabled={aiState === "loading"}
              className="press-feedback"
              style={{ width: "100%", padding: "10px 0", borderRadius: 10, fontSize: 11, fontWeight: 800, letterSpacing: 2, fontFamily: mono, cursor: "pointer", background: "linear-gradient(135deg,#6366f122,#6366f10e)", color: "#a5b4fc", border: "1px solid #6366f144" }}
            >
              {aiState === "loading" ? t("quests.goalRitual.aiLoading") : `✦ ${t("quests.goalRitual.aiSuggest")}`}
            </button>
            <div style={{ fontSize: 10, color: "#64748b", marginTop: 6, textAlign: "center" }}>
              {aiState === "failed" ? t("quests.goalRitual.aiFailed") : t("quests.goalRitual.aiSuggestHint")}
            </div>
            {suggestions.length > 0 && (
              <div style={{ display: "grid", gap: 8, marginTop: 10 }}>
                {suggestions.map((s, i) => (
                  <div key={i} style={{ padding: "10px 12px", borderRadius: 10, background: "rgba(255,255,255,0.03)", border: `1px solid ${CATEGORY_COLORS[s.category] || "#6366f1"}33` }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 }}>
                      <div style={{ minWidth: 0 }}>
                        <div style={{ fontSize: 12, fontWeight: 700, color: "#e2e8f0", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{s.title}</div>
                        <div style={{ fontSize: 9, color: CATEGORY_COLORS[s.category] || "#94a3b8", fontFamily: mono, marginTop: 2 }}>{labels[s.category]} · {s.milestones.length} ✦</div>
                      </div>
                      <button onClick={() => adoptSuggestion(s)} className="press-feedback" style={{ flexShrink: 0, fontSize: 9, fontWeight: 800, letterSpacing: 1, fontFamily: mono, padding: "6px 10px", borderRadius: 8, cursor: "pointer", background: "rgba(52,211,153,0.1)", color: "#34d399", border: "1px solid #34d39944" }}>{t("quests.goalRitual.useSuggestion")}</button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {drafts.map((draft, dIdx) => (
          <div key={draft.key} style={{ marginBottom: 14, padding: "14px", borderRadius: 14, background: "rgba(255,255,255,0.025)", border: "1px solid rgba(148,163,184,0.12)" }}>
            <div style={{ fontSize: 9, color: "#64748b", fontFamily: mono, letterSpacing: 2, marginBottom: 8 }}>{t("quests.goalRitual.goalLabel", { index: dIdx + 1 })}</div>
            <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 10 }}>
              {Object.keys(GOAL_CATEGORY_TO_STAT).map(cat => (
                <button key={cat} onClick={() => updateDraft(draft.key, { category: cat })} className="press-feedback" style={{
                  fontSize: 10, fontWeight: 700, padding: "5px 10px", borderRadius: 999, cursor: "pointer", fontFamily: "'Outfit',sans-serif",
                  background: draft.category === cat ? `${CATEGORY_COLORS[cat]}22` : "rgba(255,255,255,0.03)",
                  color: draft.category === cat ? CATEGORY_COLORS[cat] : "#64748b",
                  border: `1px solid ${draft.category === cat ? CATEGORY_COLORS[cat] + "66" : "rgba(148,163,184,0.15)"}`,
                }}>{labels[cat]}</button>
              ))}
            </div>
            <input
              value={draft.title}
              onChange={e => updateDraft(draft.key, { title: e.target.value })}
              placeholder={t("quests.goalRitual.titlePlaceholder")}
              style={{ ...inputStyle, marginBottom: 10, fontWeight: 700 }}
            />
            <div style={{ fontSize: 9, color: "#475569", fontFamily: mono, letterSpacing: 1.5, marginBottom: 6 }}>{t("quests.goalRitual.milestonesLabel")}</div>
            <div style={{ display: "grid", gap: 6 }}>
              {draft.milestones.map((m, mIdx) => (
                <input
                  key={mIdx}
                  value={m}
                  onChange={e => updateMilestone(draft.key, mIdx, e.target.value)}
                  placeholder={t("quests.goalRitual.milestonePlaceholder", { index: mIdx + 1 })}
                  style={{ ...inputStyle, fontSize: 12, padding: "8px 12px" }}
                />
              ))}
            </div>
            {draft.milestones.length < 5 && (
              <button onClick={() => updateDraft(draft.key, { milestones: [...draft.milestones, ""] })} style={{ marginTop: 8, fontSize: 10, color: "#64748b", background: "transparent", border: "none", cursor: "pointer", fontFamily: mono }}>{t("quests.goalRitual.addMilestone")}</button>
            )}
          </div>
        ))}

        {drafts.length < 3 && (
          <button onClick={() => setDrafts(ds => [...ds, emptyDraft()])} className="press-feedback" style={{ width: "100%", padding: "10px 0", marginBottom: 16, borderRadius: 12, fontSize: 11, fontWeight: 700, fontFamily: mono, letterSpacing: 1, cursor: "pointer", background: "transparent", color: "#64748b", border: "1px dashed rgba(148,163,184,0.25)" }}>{t("quests.goalRitual.addGoal")}</button>
        )}

        <button
          onClick={handleConfirm}
          disabled={validDrafts.length === 0}
          className="press-feedback"
          style={{
            width: "100%", padding: 14, borderRadius: 12, fontSize: 13, fontWeight: 700, letterSpacing: 2, fontFamily: "'Cinzel',serif", cursor: validDrafts.length === 0 ? "default" : "pointer",
            background: validDrafts.length === 0 ? "rgba(255,255,255,0.03)" : "linear-gradient(135deg,#6366f126,#6366f112)",
            color: validDrafts.length === 0 ? "#475569" : "#a5b4fc",
            border: `1px solid ${validDrafts.length === 0 ? "rgba(148,163,184,0.12)" : "#6366f144"}`,
            transition: "all 0.3s",
          }}
        >
          {t("quests.goalRitual.confirm")}
        </button>
        <button onClick={onSkip} style={{ width: "100%", padding: "12px 0 4px", background: "transparent", border: "none", color: "#475569", fontSize: 11, cursor: "pointer", fontFamily: "'Outfit',sans-serif" }}>
          {t("quests.goalRitual.skip")}
        </button>
      </div>
    </div>
  );
}
