default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_P8_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    # Clean up old ephemeral certificates since GitHub runners are destroyed after each run
    require 'spaceship'
    Spaceship::ConnectAPI::Certificate.all.each do |c|
      if c.certificate_type.to_s.include?("DISTRIBUTION")
        UI.message("Revoking old certificate: #{c.id}")
        begin
          c.delete!
        rescue => e
          UI.error("Failed to delete certificate: #{e}")
        end
      end
    end

    cert(
      api_key: api_key,
      keychain_path: "~/Library/Keychains/fastlane_tmp_keychain-db",
      keychain_password: ""
    )
    sigh(
      api_key: api_key,
      app_identifier: "com.solotodo.app"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "App.xcodeproj",
      profile_name: ENV["sigh_com.solotodo.app_appstore_profile-name"],
      code_sign_identity: "Apple Distribution"
    )

    build_app(
      workspace: "App.xcworkspace", 
      scheme: "App",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "com.solotodo.app",
      skip_waiting_for_build_processing: true
    )
  end
end
