export const FEATURE_ICON_NAMES = {
  quests_basic: "star",
  stats_view: "chart",
  settings: "bolt",
  calendar: "calendar",
  habit_tracker: "habit",
  emergency_quests: "bolt",
  quest_filters: "chart",
  analytics: "chart",
  ai_task_scan: "scan",
  music: "music",
  goals: "goal",
  training_tab: "focus",
  micro_habits: "habit",
  vision_board: "star",
  focus_mode: "focus",
  ai_quest_desc: "scan",
  achievements: "trophy",
  weekly_quests: "calendar",
  dawn_dusk: "bolt",
  ai_coach: "scan",
  dungeons: "gate",
  shop: "shop",
  gem_shop: "gem",
  equipment: "equip",
  chained_quests: "chain",
  story: "story",
  sanctum: "sanctum",
  ai_verification: "scan",
  shadow_army: "shadow",
  codex: "codex",
  ai_dynamic_quests: "scan",
  jobs: "job",
  formations: "shadow",
  challenges: "trophy",
  hidden_quests: "star",
  soul_link: "link",
  charisma_dungeons: "gate",
  named_shadows: "shadow",
  seasons: "season",
  multiplayer: "link",
};

export function getFeatureIconName(key) {
  return FEATURE_ICON_NAMES[key] || "star";
}
